version: '3.6'

services:

  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "7000:15672"
      - "7001:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmquser
      - RABBITMQ_DEFAULT_PASS=some_password

  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
    restart: always

  redis_emoticons:
    image: redis:5-alpine
    ports:
      - 6380:6379
    restart: always